networks:
  spichka-network:
    #driver: bridge
    external: true
    # if external then: docker network create spichka-network

#volumes:
#  # Optional Test: nginx, comment me
#  static_data:
#  media_data:
#  next_cache:


services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    # In production we recommend running an external systemd nginx for TLS termination
    # so the frontend does not need an external port mapped. If you want to expose
    # the container directly (not recommended), uncomment the following ports mapping.
    ports:
       - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    expose:
      - "3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - spichka-network

  # Optional (for Testing only)
  # Nginx load balancer for prod — will proxy requests to frontend service
  #nginx:
  #  build:
  #    context: ./nginx
  #    dockerfile: Dockerfile
  #  container_name: front-nginx_prod
  #  volumes:
  #    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #    - static_data:/app/static
  #    - media_data:/app/media
  #  ports:
  #    - 80:80
  #    - 443:443
  #    # Expose prod nginx HTTP on host port 3000 so you can test frontend at http://localhost:3000
  #    #- "3000:80"
  #  depends_on:
  #    - frontend
  #  restart: unless-stopped
  #  networks:
  #    - spichka-network

# To scale frontend for testing in prod run: docker compose -f docker-compose.prod.yml up --scale frontend=2 --build
# or: docker compose -f .\docker-compose.prod.yml up -d --no-deps --scale frontend=2 frontend
