import type { Metadata } from "next";
import {
  jost,
  libreFranklin,
  comfortaa,
  unbounded,
  geologica,
} from "./ui/fonts";
import "./globals.css";
import Providers from "@/components/shared/ui/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} ${comfortaa.variable} ${libreFranklin.variable} ${unbounded.variable} ${geologica.variable}`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
