import type { Metadata } from "next";
import { jost, libreFranklin } from "./ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.variable} ${libreFranklin.variable}`}>
        {children}
      </body>
    </html>
  );
}
