name: Deploy Frontend to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
     
      - name: 🚀 Notify Pipeline Start
        uses: appleboy/telegram-action@master
        with:
          to: -1002824319072
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message_thread_id: 11299
          format: markdown
          message: |
            🔄 *Пайплайн Deploy Frontend to Production запущен*
            
            📦 Репозиторий: `${{ github.repository }}`
            🌿 Ветка: `${{ github.ref_name }}`
            👤 Инициатор: `${{ github.actor }}`
            💬 Коммит: `${{ github.event.head_commit.message }}`
            🔗 [Открыть в CI/CD](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            ⏱️ Ожидание завершения...
            📎 ID задачи: `${{ github.run_id }}`

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Кеширование node_modules
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production

      - name: DNS & SSH reachability check
        run: |
          sudo apt-get update -y
          sudo apt-get install -y dnsutils netcat-openbsd
          echo "DNS:"
          dig +short "${{ secrets.HOST }}" || true
          echo "Ping:"
          ping -c 3 "${{ secrets.HOST }}" || true
          echo "SSH port:"
          nc -vz "${{ secrets.HOST }}" 22 || true

      - name: Test SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "SSH connection successful!"
            whoami
            pwd
            ls -la
    
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/spichka/Spichka-mobile-web
            git pull origin main
            ./deploy.sh

      
      - name: 🎉 Notify Success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: -1002824319072
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message_thread_id: 11299
          format: markdown
          message: |
            ✅ *Пайплайн Deploy Frontend to Production завершён успешно*
            
            📦 Репозиторий: `${{ github.repository }}`
            🌿 Ветка: `${{ github.ref_name }}`
            👤 Инициатор: `${{ github.actor }}`
            💬 Коммит: `${{ github.event.head_commit.message }}`
            🔗 [Открыть в CI/CD](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            ⏱️ Время выполнения: `${{ job.status }}`
            📄 Результат: Frontend успешно развёрнут на сервере! 🚀
            🌐 Приложение доступно на порту 3000

      - name: 💥 Notify Failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: -1002824319072
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message_thread_id: 11299
          format: markdown
          message: |
            ❌ *Пайплайн Deploy Frontend to Production завершился с ошибкой*
            
            📦 Репозиторий: `${{ github.repository }}`
            🌿 Ветка: `${{ github.ref_name }}`
            👤 Инициатор: `${{ github.actor }}`
            💬 Коммит: `${{ github.event.head_commit.message }}`
            🔗 [Открыть в CI/CD](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            📍 Этап: Проверьте логи для определения проблемного шага
            💥 Ошибка: Пайплайн прерван на одном из этапов
            
            Возможные причины:
            • Ошибки в коде или зависимостях
            • Проблемы с Docker build
            • Недоступность сервера
            • Проблемы с переменными окружения

    
      - name: ⚠️ Notify Cancellation
        if: cancelled()
        uses: appleboy/telegram-action@master
        with:
          to: -1002824319072
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message_thread_id: 11299
          format: markdown
          message: |
            ⚠️ *Пайплайн Deploy Frontend to Production был отменён*
            
            📦 Репозиторий: `${{ github.repository }}`
            🌿 Ветка: `${{ github.ref_name }}`
            👤 Инициатор: `${{ github.actor }}`
            💬 Коммит: `${{ github.event.head_commit.message }}`
            🔗 [Открыть в CI/CD](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            🛑 Пайплайн был остановлен вручную или по тайм-ауту
